Create database tables
nekozestrtgy/chat-space pull request #1
Opened 2019-02-04 12:17 UTC by nekozestrtgy

README.mdを編集し、各テーブルを作成した

2019-02-07 08:52 UTC, yuki-uchida requested changes

2019-02-07 08:52 UTC, yuki-uchida commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
refference型にしましょう！integerでもあるんですが。外部テーブルである場合にはrefferece型が使えます

2019-02-07 08:52 UTC, yuki-uchida commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
こちらも

2019-02-09 07:45 UTC, nekozestrtgy commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
修正しました。

2019-02-11 10:17 UTC, ghost requested changes

2019-02-11 10:17 UTC, hiroki5123 commented on README.md
> +|description|text||
このカラムは必要ないのですが、ある分には問題ないので修正はお任せします。

2019-02-11 10:17 UTC, hiroki5123 commented on README.md
> +- has_many :messages
アソシエーションが一つ足りません

2019-02-11 10:17 UTC, hiroki5123 commented on README.md
> +- has_many :messages
アソシエーションが一つ足りません

2019-02-11 10:18 UTC, yuki-uchida requested changes

2019-02-11 10:18 UTC, yuki-uchida commented on README.md
> +|references|user|null: false, foreign_key: true|
順番が逆になってますね

2019-02-11 10:18 UTC, yuki-uchida commented on README.md
> +|references|user|null: false, foreign_key: true|
こちらも

2019-02-11 10:44 UTC, nekozestrtgy commented on README.md
> +- has_many :messages
すみません、よくわかりません。
足りないとしたら、group-user間のアソシエーションかと思いますが、そこが多対多なので、間にmembersテーブルを入れているのではないのでしょうか。

2019-02-11 10:45 UTC, nekozestrtgy commented on README.md
> +|references|user|null: false, foreign_key: true|
修正しました。
reference部分のcolumnとtype部分を入れ替えました。

2019-02-11 10:48 UTC, hiroki5123 commented on README.md
> +- has_many :messages
おっしゃる通りですが、中間テーブルを経由してusersテーブルと多対多の関係になっているアソシエーションを定義する必要があります。
現在はmembersテーブルとのアソシエーションが組まれていますが、usersテーブルへのアソシエーションも定義してください。

2019-02-11 11:16 UTC, nekozestrtgy commented on README.md
> +- has_many :messages
そういうことだったんですね！
アソシエーションを追加する修正を行いました。

2019-02-11 11:32 UTC, ghost requested changes

2019-02-11 11:32 UTC, hiroki5123 commented on README.md
> +- has_many :users
中間テーブルを経由してください！

2019-02-11 11:32 UTC, hiroki5123 commented on README.md
> +- has_many :groups
こちらも中間テーブルを経由してください！

2019-02-11 11:56 UTC, nekozestrtgy commented on README.md
> +- has_many :groups
修正しました。
Userテーブルとgroupテーブルのアソシエーションにthrough: :membersを追記しました。

2019-02-11 11:58 UTC, ghost approved these changes
LGTMです！

2019-02-11 12:12 UTC, merged