Setup-message-ajax
nekozestrtgy/chat-space pull request #8
Opened 2019-02-18 12:19 UTC by nekozestrtgy

メッセージの投稿を非同期通信で行えるよう実装した。

2019-02-18 12:22 UTC, nekozestrtgy commented
## what
jsファイルの作成、messageコントローラーの編集、jbuilderファイルの作成を行った。

## why
メッセージの送信を非同期通信で行えるようにするため。

2019-02-18 12:37 UTC, ghost requested changes

2019-02-18 12:37 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +                ${message.user_name}
これ画像送れなくないですか？

2019-02-18 12:37 UTC, hiroki5123 commented
画像も送れるように修正しましょう

2019-02-19 08:46 UTC, nekozestrtgy commented on app/assets/javascripts/message.js
> +                ${message.user_name}
> 画像も送れるように修正しましょう
画像も送れるよう修正しました。

2019-02-19 08:53 UTC, ReoKuriyama requested changes
現状だとおそらく一度画像を送ったあとだと毎回その画像が送られてしまうのでそこも修正をお願いします

2019-02-19 08:53 UTC, ReoKuriyama commented on app/assets/javascripts/message.js
> +                ${ message.text ?
messageとtext同時に送られた場合はどうしましょうか

2019-02-19 08:53 UTC, ReoKuriyama commented on app/controllers/messages_controller.rb
> +        format.html { redirect_to group_messages_path(@group) }
htmlレスポンスは使わなくなるので消しましょう

2019-02-19 10:18 UTC, nekozestrtgy commented on app/assets/javascripts/message.js
> +                ${ message.text ?
修正しました。

2019-02-19 10:18 UTC, nekozestrtgy commented on app/controllers/messages_controller.rb
> +        format.html { redirect_to group_messages_path(@group) }
こちらも修正しました。

2019-02-19 10:21 UTC, ReoKuriyama approved these changes
LGTMです
修正的確でした 👍

2019-02-19 10:24 UTC, merged